name: Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    name: ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: run migrations
        run: make migrate
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
          POSTGRES_DATABASE_URL: postgres://postgres:password@localhost:5432/postgres

      - name: Generate coverage file
        if: matrix.version == 'stable' && (github.ref == 'refs/heads/master' || github.event_name == 'pull_request')
        uses: actions-rs/tarpaulin@v0.1
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
          POSTGRES_DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
        with:
          version: '0.18.2'
          args: "--all-features --no-fail-fast --workspace=database/db-sqlx-postgres,. -t 1200"

      - name: Upload to Codecov
        if: matrix.version == 'stable' && (github.ref == 'refs/heads/master' || github.event_name == 'pull_request')
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: cobertura.xml
